name: Bilira Bot

on:
  schedule:
    - cron: "0 0 * * *"  # every midnight
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install python-telegram-bot==13.15 pyppeteer

      - name: Check secrets
        run: |
          if [ -z "$BOT_TOKEN" ]; then
            echo "❌ BOT_TOKEN is empty."
            exit 1
          fi
          if [ -z "$CHAT_ID" ]; then
            echo "❌ CHAT_ID is empty."
            exit 1
          fi
          echo "✅ Secrets OK."
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Run Bilira Bot
        run: python bilira_bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
